Reoptimize
leeping/forcebalance pull request #161
Opened 2019-10-10 04:07 UTC by jstoppelman

Addition of reopt.py files into the tools directory of ForceBalance. Requested review of the code setup for the "reopt_script_combined" folder and "reopt_script_separate" directories. The code is essentially the same, except the "reopt_script_separate" contains an engines.py code with separate classes and methods for use by the main code, while the "combined" version contains all of these methods into one script.

2020-07-31 17:00 UTC, jstoppelman commented
Hi Lee-Ping, the Drude study should go with the other pull request I have open, I must have mixed up the files. Maybe it's best to have these separate? I updated openmmio.py to be consistent with the current version in ForceBalance and removed the Drude directory. I also updated the About.txt file.

2020-09-28 02:26 UTC, leeping requested changes

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -# Special error which is thrown when TINKER .arc data is detected in a .xyz file
This needs to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> +QuantumVariableNames = {'qcrems', 'qctemplate', 'charge', 'mult', 'qcsuf', 'qm_ghost', 'qm_bondorder', 'psi4template', 'psi4fragn',                         'psi4args'}
There are too many spaces between psi4fragn and psi4args.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -#
This needs to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -# Special error which is thrown when TINKER .arc data is detected in a .xyz file
(As in, the "red" part needs to be put back and the "green" part needs to be removed.)

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -        logger.debug('Note: Cannot import optional dcdlib module to read/write DCD files.\n')
The `logger.debug` messages are newer, so the changes here need to be reverted.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> +        logger.info('The pdb module cannot be imported (Cannot read/write PDB files)')
The `logger.debug` messages are newer, so the changes here need to be reverted.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> +        logger.info('The Mol2 module cannot be imported (Cannot read/write Mol2 files)')
The `logger.debug` messages are newer, so the changes here need to be reverted.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -            elems = nx.get_node_attributes(self,'e')
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -    logger.warning("Cannot import optional NetworkX module, topology tools won't work\n.")
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -        totMass = sum([PeriodicTable.get(self.elem[i], 0.0) for i in range(self.na)])
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -        totMass = sum([PeriodicTable[self.elem[i]] for i in range(self.na)])
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -        except ActuallyArcError:
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -                    try:
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2020-09-28 02:26 UTC, leeping commented on src/molecule.py
> -                # Although is isn't exactly up to spec,
The lines highlighted in red are newer, so the changes here need to be reverted, perhaps by merging the master branch into this branch.

2021-02-10 18:40 UTC, leeping commented
Closing this PR per discussion with @jstoppelman .

2021-02-10 18:40 UTC, closed without merging